# Generated by Django 2.2 on 2020-04-03 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answers',
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AlterField(
            model_name='answer',
            name='comment',
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AlterField(
            model_name='answer',
            name='duration',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='question',
            name='dependencies',
            field=models.ManyToManyField(blank=True, related_name='question_dependencies', to='profiles_api.Subtopic'),
        ),
    ]
