# Generated by Django 2.2 on 2020-02-29 12:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0002_profilefeeditem'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionFeedItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('topic', models.CharField(max_length=255)),
                ('subtopic', models.CharField(max_length=255)),
                ('dependencies', models.CharField(max_length=255)),
                ('question', models.CharField(max_length=1024)),
                ('correctAnswers', models.CharField(max_length=255)),
                ('appendix', models.CharField(max_length=255)),
                ('hint', models.CharField(max_length=1024)),
                ('imageSrc', models.CharField(max_length=1024)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
