# Generated by Django 2.2 on 2020-04-12 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0002_auto_20200404_0128'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='validation',
            new_name='validation_type',
        ),
        migrations.AlterField(
            model_name='answer',
            name='comment',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='correct',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='skipped',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
