# Generated by Django 2.2 on 2020-04-12 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0003_auto_20200412_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='validation_type',
            field=models.CharField(choices=[('standardValidation', ''), ('multipleStrings', 'multipleStrings'), ('singleFraction', 'singleFraction')], max_length=255),
        ),
    ]
