# Generated by Django 2.2 on 2020-03-09 19:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0003_questionfeeditem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionfeeditem',
            name='appendix',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='questionfeeditem',
            name='dependencies',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='questionfeeditem',
            name='hint',
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AlterField(
            model_name='questionfeeditem',
            name='imageSrc',
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Subtopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('html', models.CharField(blank=True, max_length=1024)),
                ('topic', models.ManyToManyField(to='profiles_api.Topic')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
