# Generated by Django 2.2 on 2020-04-25 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0004_auto_20200412_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtopic',
            name='html',
            field=models.CharField(blank=True, max_length=8191),
        ),
    ]
