# Generated by Django 2.2 on 2020-04-25 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0005_auto_20200425_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='comment',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
        migrations.AlterField(
            model_name='answer',
            name='correct',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='answer',
            name='skipped',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
