# Generated by Django 2.2 on 2020-04-25 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0006_auto_20200425_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='html',
            field=models.CharField(blank=True, max_length=8191),
        ),
    ]
