# Generated by Django 2.2 on 2020-04-25 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0007_auto_20200425_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theorypage',
            name='html',
            field=models.CharField(blank=True, max_length=8191),
        ),
    ]
