# Generated by Django 2.2 on 2020-04-29 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0008_auto_20200425_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='completedtest',
            name='test',
            field=models.ForeignKey(blank=True, default=8, on_delete=django.db.models.deletion.CASCADE, to='profiles_api.Test'),
            preserve_default=False,
        ),
    ]
