# Generated by Django 2.2 on 2020-05-02 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0009_completedtest_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='difficulty',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='question',
            name='set_difficulty',
            field=models.IntegerField(default=3),
        ),
    ]
