# Generated by Django 2.2 on 2020-08-01 13:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0010_auto_20200502_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='difficulty_updated_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='facility',
            field=models.FloatField(default=0.5),
        ),
        migrations.AddField(
            model_name='question',
            name='facility_updated_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='answer',
            name='duration',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='question',
            name='set_difficulty',
            field=models.IntegerField(default=0),
        ),
    ]
