# Generated by Django 2.2 on 2020-08-15 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0012_proficiency'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='type',
            field=models.CharField(choices=[('standard', 'standard'), ('personal', 'personal')], default=('standard', 'standard'), max_length=255),
        ),
    ]
