# Generated by Django 2.2 on 2020-08-15 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0013_test_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='type',
            field=models.CharField(choices=[('standard', 'standard'), ('personal', 'personal')], default='standard', max_length=255),
        ),
    ]
