# Generated by Django 2.2 on 2020-08-15 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0014_auto_20200815_1648'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='type',
            new_name='creation_type',
        ),
    ]
