# Generated by Django 2.2 on 2020-08-15 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0016_remove_test_creation_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='creation_type',
            field=models.CharField(choices=[('standard', 'standard'), ('personal', 'personal')], default='standard', max_length=255),
        ),
    ]
