# Generated by Django 2.2 on 2020-08-15 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0017_test_creation_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='creation_type',
            field=models.CharField(default='standard', max_length=255),
        ),
    ]
