# Generated by Django 2.2 on 2020-08-16 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0018_auto_20200815_1712'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='completedtest',
            name='recommendedSubtopics',
        ),
        migrations.AddField(
            model_name='question',
            name='number_of_answers',
            field=models.IntegerField(default=0),
        ),
    ]
