# Generated by Django 2.2 on 2020-08-16 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0019_auto_20200816_2119'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtopic',
            name='answers_since_update',
            field=models.IntegerField(default=0),
        ),
    ]
