# Generated by Django 2.2 on 2020-08-18 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0020_subtopic_answers_since_update'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proficiency',
            old_name='number_of_answers',
            new_name='answers_since_update',
        ),
        migrations.RemoveField(
            model_name='proficiency',
            name='level',
        ),
    ]
