# Generated by Django 2.2 on 2020-08-18 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0021_auto_20200818_2236'),
    ]

    operations = [
        migrations.AddField(
            model_name='proficiency',
            name='level',
            field=models.IntegerField(default=1),
        ),
    ]
