# Generated by Django 3.1.1 on 2020-09-26 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0022_proficiency_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theorypage',
            name='test',
        ),
    ]
