# Generated by Django 3.1.1 on 2020-10-04 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0023_remove_theorypage_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='proficiency',
            name='number_of_answers',
            field=models.IntegerField(default=0),
        ),
    ]
